### ISSUE TITLE
todo: enable Travis CI

### ISSUE THREAD

**Issue by DanielRuf** [kitze/react-hanger#10]
Currently it is not enabled / active (for PRs and commits).

**Comment by DanielRuf** [comment]
What we also have to do is to install React on CI to test the module: https://travis-ci.com/DanielRuf/react-hanger/jobs/155062186#L488

**Comment by RIP21** [comment]
5144415 fixed on. @kitze enable Travis in the Travis UI if it's not there yet and add badge?

**Comment by DanielRuf** [comment]
Not sure what you mean but this is just a readme change.
