### ISSUE TITLE
useArray clear method didn't need parameters (wrong TS type definition)

### ISSUE THREAD

**Issue by Alex-Ferreli** [kitze/react-hanger#18]
Hi! Thanks for the awesome collection of Hooks.

In TS definition the clear method of useArray Hooks have this signature:

```typescript
clear: (value: T) => void;
```
[here](https://github.com/kitze/react-hanger/blob/master/src/index.d.ts#L33)

The clear method should not need a parameter right?
Can i do a PR to fix it?

Thanks in advance!

**Comment by RIP21** [comment]
It's clearly a mistake.
Please open PR. Will merge.

**Comment by Alex-Ferreli** [comment]
Done. Sorry for the first pull request, i was referencing another issue (wrong copy-past from another PR).

Let me know if i should do something else.

**Comment by RIP21** [comment]
Fixed in 1.1.4
