### ISSUE TITLE
Add array.move to useArray for drag and drop sort

### ISSUE THREAD

**Issue by neves** [kitze/react-hanger#22]
https://github.com/sindresorhus/array-move/blob/master/index.js

**Comment by RIP21** [comment]
Would be nice.
There is a plan to rewrite `react-hanger` in Typescrpt and to change the API to more idiomatic and correct so it's easier to work with it using `react-hooks` ESLint rules. Because right now it's a pain in the ass.
So I'll consider add this one to the API too.

**Comment by kitze** [comment]
@RIP21 yeah it would be awesome if it's rewritten in TS!

**Comment by RIP21** [comment]
Fixed by 5144415
Thanks for suggestion.
@kitze FYI also rewritten to TS and also few `useMemo` improvements added as well as the few tests (finally!)

**Comment by RIP21** [comment]
@neves take look at the latest version. (1.2.0)
