### ISSUE TITLE
Add allcontributors bot to the repo

### ISSUE THREAD

**Issue by RIP21** [kitze/react-hanger#24]
Hey @kitze 
https://allcontributors.org/docs/en/bot/installation
I don't have access I think, but can you add contributors bot here? It's going to be nice to have for contributors (e.g. me and many others) to be mentioned.

**Comment by kitze** [comment]
@RIP21 added, no idea how it works

@all-contributors please add @RIP21 for infrastructure, tests and code

**Comment by RIP21** [comment]
Nice :) Only 2 years after :D

**Comment by kitze** [comment]
@RIP21 just imagine the progress we'll make in 2023
