### ISSUE TITLE
Remove useOnMount, useOnUnmount, and useLifecycleHooks

### ISSUE THREAD

**Issue by kitze** [kitze/react-hanger#27]
I don't think these are that useful and they can just be confusing for beginners who're just getting started with hooks. 
What do you think @RIP21 ?

**Comment by RIP21** [comment]
@kitze I think they are helpful a bit but in the same, I must admit the person that uses them, should understand `useEffect` nature. So, I think we can remove them.
Personally, I never use them cause just `useEffect` is good for me.

**Comment by kitze** [comment]
@RIP21 exactly!

**Comment by RIP21** [comment]
@kitze so. KILL IT :D
BTW, fix two other issues we have here :P Description, tags and stuff like that. And we also need to chat about V2 :P
