### ISSUE TITLE
Move each hook to its own file for individual importing

### ISSUE THREAD

**Issue by michaelauderer** [kitze/react-hanger#29]
Each hook should be in its own file so that users can import like this:

`import useArray from 'react-hanger/useArray'`

This ensures that only that one hook is imported into the file, rather than the whole library.

**Comment by RIP21** [comment]
Sure, will add this one to v2 :) Thanks.

**Comment by RIP21** [comment]
@michaelauderer is done. Please test `v2.0.0` note that there is a small breaking change.
