### ISSUE TITLE
CodeSandbox  shows an error

### ISSUE THREAD

**Issue by Ofer-Gal** [kitze/react-hanger#32]
The link Open in CodeSandbox shows a warning  and does not work

**Comment by RIP21** [comment]
Link please?

**Comment by RIP21** [comment]
Oh, got it. Someday will fix that thing.

**Comment by GabLeRoux** [comment]
I updated the packages, but still fails with this

> func.apply is not a function

https://codesandbox.io/s/react-hanger-example-zvbeg

**Comment by exlame** [comment]
I've updated a codeSandbox because it was outdated
https://codesandbox.io/s/react-hanger-example-2rt8w
