### ISSUE TITLE
Use BaseSyntheticEvent to support React Native

### ISSUE THREAD

**Issue by jckw** [kitze/react-hanger#33]
First of all thank you for making React Hanger! It's great + I use it in every React project I work on. 

Creating a React Native app using Typescript raises a typing error for the `onChange` function supplied by useInput. 

Instead of typing the function to accept only a React.SyntheticEvent argument, it could alternatively be typed as accepting a [React.BaseSyntheticEvent](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1037) argument that would support both SyntheticEvent (used by react-dom) and NativeSyntheticEvent (used by react-native).

This would mean that react-hanger's useInput can be used in React Native Typescript projects straight out of the box.

**Comment by RIP21** [comment]
@jckw gotcha. Will do that in the next version.

**Comment by RIP21** [comment]
Fixed in 2.1.0
