### ISSUE TITLE
Feature idea: `useArray` and modify by element id 

### ISSUE THREAD

**Issue by nkint** [kitze/react-hanger#42]
Hi!
I'm using `useArray` and I'm ok with it but I'd like to be able to modify an element by id and have a re-render.

I've tested it locally and this works for me:

```ts
	const modifyElementById = useCallback(
		(id: string, newValue: Partial<T>) =>
			setValue(arr => arr.map(v => (v.id === id ? { ...v, ...newValue } : v))),
		[],
	);
```

I'd like to write a PR (it is a super simple idea) but I open this issue to first ask what do you think about it.

**Comment by kitze** [comment]
hey @nkint, this sounds like a great addition, so please feel free to open a PR!
