### ISSUE TITLE
modifyById() with Typescript

### ISSUE THREAD

**Issue by MarkoniusDev** [kitze/react-hanger#44]
The function modifyById() isn't found. 

When defining an array, there is no practical way to modify an element of it. 

```tsx
const list = useArray<Object>(initialArray);

array.modifyById()
```

When hovering the `array.modifyById()` VSCode's error is : 

```
Propety 'modifyById' does not exist on type UseArray<Object>
```

**Comment by RIP21** [comment]
Version with this feature is not published yet.

**Comment by MarkoniusDev** [comment]
This makes sense now. 

Modifying an element of the array might be tricky without this funtion
