### ISSUE TITLE
'useNumber' does not respect 'lowerLimit' and 'upperLimit' when using 'setValue'

### ISSUE THREAD

**Issue by OrLavy** [kitze/react-hanger#47]
First, thank you for this awesome library !

The 'useNumber' hook does not respect it's own option when using 'setValue'.

Example: 

`let myNumber = useNumber(10, { lowerLimit: 0, upperLimit: 100 });`
`myNumber.setValue(200);`

`console.log(myNumber.value); // Will have value of 200, even though the upper limit is 100.`

EDIT : opened a [PR](https://github.com/kitze/react-hanger/pull/48) fixing the problem.

**Comment by RIP21** [comment]
Feels like expected behavior. Although simple check with error can be added surely.

**Comment by RIP21** [comment]
@OrLavy sorry for being super slow with publishing.
Your stuff is published here
https://github.com/kitze/react-hanger/releases/tag/v2.2.0

Thanks a lot for the contribution!
