### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by michael-woodward-spok** [kitze/react-hanger#52]
The NPM package is out of date. I am looking to use the `modifyById` function from the `useArray` hook, but it appears as if that hook doesn't have this function yet in the most recent NPM release. 

Thanks for the great hooks!

**Comment by RIP21** [comment]
Sure man. Will do today.

**Comment by RIP21** [comment]
But in the evening. Loaded with work... Will try to squeeze contributions docs too.

**Comment by kitze** [comment]
@RIP21 can we set up the most basic CI in the world so we don't have to do this manually

**Comment by RIP21** [comment]
I'm not sure if I have access to do that :( Can you please go and make my access better? Unsure if possible tho. Wanted it to use Github Actions and stuff like that. Plus I want to install some helpful bots too.
I had plan to go through issues etc this weekend and then gradually start to add more stuff from you :)

**Comment by RIP21** [comment]
@michael-woodward-spok hey man. Updated!
https://github.com/kitze/react-hanger/releases/tag/v2.2.0

**Comment by michael-woodward-spok** [comment]
Thanks guys!
