### ISSUE TITLE
v2.4.3 missing index.js on npm

### ISSUE THREAD

**Issue by nghiepit** [kitze/react-hanger#76]
Seems to look like you forgot to run `yarn build` script before publishing on npm.

https://unpkg.com/react-hanger@2.4.3
> Cannot find "/index.js" in react-hanger@2.4.3

**Comment by RIP21** [comment]
Probably. Will check tomorrow. Thanks.

**Comment by RIP21** [comment]
Fixed that. Published from wrong folder :)
